### PR TITLE
Author contributions

### PR DESCRIPTION
**Pull request by namn12**

### CODE REVIEW

**Comment by namn12** [comment]
@aarmey the authorline is based on what is currently in the manuscript as it is. after evaluating the manuscript in current form, nearly everything presented (ie all the data, model, and writing) was performed in substantial form by SV, NKN, and AW. however, AF and AL have done a lot of work for the project that did not see its way to the manuscript in its current form. likewise, most of the work performed by FM on thmm is not directly presented in the manuscript in its current form. though i know FM has been working substantially on the project and she has results that will soon be a part of the paper (ie cell cycle phase, etc). there is a lot at play and i dont think this is a finalized authorline (though the contribution descriptions should be relatively robust in the current form) and i decided to keep everyone on for the time being with understanding that things can possibly change. i should also note that i consulted the first author @shak360 before i made this decision. we acknowledge that you have the final say in the authorline. let us know what you think and i am happy to talk more about this.

**Comment by shak360** [comment]
#117

**Comment by aarmey** [comment]
Also you should use some consistent rule for initials ordering (just so it's not random). Say alphabetical?

**Comment by namn12** [comment]
> Also you should use some consistent rule for initials ordering (just so it's not random). Say alphabetical?

done

**Pull request merged**
