### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Farnazmdi**
Added some tests for `LineageTree` and `StateDistribution`, and more docstring to the files. 
I am not sure about the warnings though.

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Should I just "enter" when a line gets too long?!

**Comment by shak360** [comment]
no we can use autopep8 to fix those linting errors @Farnazmdi 

`autopep8 -i -a -r --max-line-length 200 lineage`

input the above into the terminal while in the lineage repository and enter

**Comment by shak360** [comment]
@aarmey Linting is done and the tests are running successfully. IDK why the reviews become stale after changes. I don't recall it doing that earlier.

**Comment by aarmey** [comment]
I'll change that setting. It's not ideal either way, but not annoying is better.

**Pull request merged**
