### PR TITLE
Guide to code

### PR DESCRIPTION
**Pull request by shak360**
Moved some functions outside of the package in the figures folder to the package as it made more sense for them to be there. I think I sufficiently changed all the imports that were affected by it.

Made a notebook on how to run our code. I realized we made a lot of functions that effectively hide the code that actually does much of the work. As such, let me know if you want me to show more about how the inner workings of the package works, instead of how a user would use it @aarmey Dr. Meyer.

### CODE REVIEW

**Comment by shak360** [comment]
The guide to the code is here: https://github.com/meyer-lab/lineage-growth/blob/79c9804953373fc455a3c0b90e0aeb651d4b9a76/Guide_to_tHMM.ipynb

**Comment by shak360** [comment]
If approved this closes #104 and #125

**Comment by namn12** [comment]
really nice work. i'll review this and the other pr in the next 1-3 days and will fix the changes on aic pr.

**Comment by aarmey** [comment]
@namn12 ready to merge when you're fine with this. Ping me when this is merged, and I'll walk through the tutorial and review the code.

**Comment by shak360** [comment]
Merging now. Feel free to ask me questions Dr. Meyer @aarmey

**Pull request merged**
