### PR TITLE
Jc fig3cartoon

### PR DESCRIPTION
**Pull request by jclagarde**
@Farnazmdi I added the cartoon for figure 3b. Take a look when you have time

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Looks great! @jclagarde Is there a way to reduce the gap between the figures? And I guess you need to `git pull` the changes from the previous merge.

**Comment by shak360** [comment]
Yea @jclagarde looks like there's merge conflicts. You can resolve them here, using the `Resolve conflicts` button.

**Comment by jclagarde** [comment]
I keep getting this error when I try to merge it. I even tried to delete the old code that was within `<<head`

Screen Shot 2020-06-25 at 10 44 12 PM

**Comment by jclagarde** [comment]
@shak360 Actually, I think I got it working now. I'm not sure what happened, I just tried commiting again and now I no longer get those error codes

**Comment by shak360** [comment]
Can you look at the Files Changed tab on the top-right of this page @jclagarde , and make sure that all the changes you want are implemented? I think some of the numbers you wanted for moving some of the images aren't there (unless you plan on doing that in another branch).

**Comment by jclagarde** [comment]
> Can you look at the Files Changed tab on the top-right of this page @jclagarde , and make sure that all the changes you want are implemented? I think some of the numbers you wanted for moving some of the images aren't there (unless you plan on doing that in another branch).

@shak360 thanks for the heads up. I just fixed them

**Comment by shak360** [comment]
@jclagarde It looks like you have some of these changes on another branch as well? But on that branch it also seems like you're replacing the cartoons with new ones? Do you wanna do that on this branch or that one? Do you mind cleaning up your branches (deleting which ones you dont need).

**Comment by jclagarde** [comment]
> @jclagarde It looks like you have some of these changes on another branch as well? But on that branch it also seems like you're replacing the cartoons with new ones? Do you wanna do that on this branch or that one? Do you mind cleaning up your branches (deleting which ones you dont need).

@shak360 Ohh okay, I made the same changes on both branches except I added the overlay for figure 3b on jc-fig3cartoon, which is the one I want to merge. I deleted the other ones so now I just have jc-fig3cartoon

**Comment by shak360** [comment]
This one doesn't have new cartoons though @jclagarde . Did you have new cartoons to upload, besides the figure 3 one for Farnaz?

**Comment by jclagarde** [comment]
> This one doesn't have new cartoons though @jclagarde . Did you have new cartoons to upload, besides the figure 3 one for Farnaz?

ah you're right, I forgot to upload the updated cartoons. I just sent a push to update the cartoons. I need to adjust the x and y positions for genfigures.py some more though

**Comment by shak360** [comment]
OK, sounds good, let me know when you're comfortable with the changes and I can review the changes and approve @jclagarde

**Comment by shak360** [comment]
Closes #300 once merged

**Comment by jclagarde** [comment]
> OK, sounds good, let me know when you're comfortable with the changes and I can review the changes and approve @jclagarde

@shak360 I finished making changes to the cartoons, and I'm comfortable with them

**Pull request merged**
