### PR TITLE
Build with manubot

### PR DESCRIPTION
**Pull request by aarmey**
Allows annotation of built manuscript. Simpler citations.

### CODE REVIEW

**Comment by aarmey** [comment]
Only issue is it's getting stuck on an equation somewhere in the methods.

**Comment by shak360** [comment]
I tried finding the \LaTeX error but can't really get anywhere. Does this error `jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 29050` ring any bells for you @aarmey

**Comment by shak360** [comment]
I have a feeling it might be due to the use of `\bm` in the `\LaTeX` writing since that is a package that needs to be included if it needs to work.

**Comment by aarmey** [comment]
I was thinking the same but want to try deleting just the first or last half of the file when I get a chance to ensure it's not something more specific...

**Comment by aarmey** [comment]
@shak360 error I was seeing was from the equation you deleted from the methods. It looks like you committed a bunch of figure files here. Can you clean this up?

**Comment by aarmey** [comment]
@shak360 in fact, please revert your commits here, then branch off this and work on a separate branch. `\bm` is not the problem. The jinja errors are before latex is called, so there's a syntax error somewhere when you see them.

**Comment by shak360** [comment]
Ready when you are @aarmey Was the error with the display-style LaTeX equation?

**Comment by aarmey** [comment]
Thanks. There were some extraneous curly braces. They were correct syntax but didn’t work with ninja for some reason. Removing them didn’t affect the output, so it was an easy fix.

**Pull request merged**
