### PR TITLE
Figures

### PR DESCRIPTION
**Pull request by shak360**

### CODE REVIEW

**Comment by shak360** [comment]
https://github.com/meyer-lab/lineage-growth/issues/151

Figures are set to long run times just for the sake of seeing how they perform at scale. Will reduce them for the sake of having a short build time.

**Comment by shak360** [comment]
Figure 7 still needs some work.

**Comment by shak360** [comment]
Sorry been busy with things, what's left to do with this again? Probably can't meet till Thursday this week, but am available remotely online to chat.

**Comment by Farnazmdi** [comment]
fix dimensions and keep pruned - notes

**Comment by aarmey** [comment]
Ok, we need to prevent forming these behemoth PRs. Remember 1 PR = 1 defined code change. Is there a minimal set of changes to get this to build so we can merge? I'd like to go through the code like I did before the major refactoring, but it has to minimally work...

**Pull request merged**
